#include <pgmspace.h>
// Production MQTT CA Certificate
// Generated from production server CA certificate
static const char ProductionRootCA[] PROGMEM =
"-----BEGIN CERTIFICATE-----\r\n"   \
"MIIDgzCCAmugAwIBAgIUQKYgGwzDHf9Ekzw+P4fFTMiWoIswDQYJKoZIhvcNAQEL\r\n"  \
"BQAwUTEkMCIGA1UEAwwbUGFya2luZyBHYXRlIFJlbW90ZSBNUVRUIENBMRwwGgYD\r\n"  \
"VQQKDBNQYXJraW5nIEdhdGUgUmVtb3RlMQswCQYDVQQGEwJJTDAeFw0yNjAxMDQx\r\n"  \
"NzAzMDhaFw0zNjAxMDIxNzAzMDhaMFExJDAiBgNVBAMMG1BhcmtpbmcgR2F0ZSBS\r\n"  \
"ZW1vdGUgTVFUVCBDQTEcMBoGA1UECgwTUGFya2luZyBHYXRlIFJlbW90ZTELMAkG\r\n"  \
"A1UEBhMCSUwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCzpcg6mWgP\r\n"  \
"BMSKd7mV4S3P4NZQEIoZjbm35RPLfK57ZxOY8ZEzKuqrSaALW3+XYcWutUIWb+Yo\r\n"  \
"z9dBpZdnkCaKdjFVmVf18frC35IbEhXRkTes6eWiA956AJx0JohLYLPSgil4GDmo\r\n"  \
"GprG68JAjdVJDti8BVVhsY7WHDXyt1SdpBYrD9Fu59cHEdK9pYY6Gav186bYKT8w\r\n"  \
"RRLhFAcPf7S1l1DMu2XDjzSdbg+Q16eeYA0BmHetQ3oBe98oDArLW6mIv0k9aZkf\r\n"  \
"rHUz1yDr1UP0GmYQSSeb1GEsncwipCkz9OyOIiQtuV/ndbamji9q5dYPO9F46wiJ\r\n"  \
"j+4Pgh3CN8bbAgMBAAGjUzBRMB0GA1UdDgQWBBQPGf4RMJGh/vIQaJO0hQTVIsaf\r\n"  \
"WTAfBgNVHSMEGDAWgBQPGf4RMJGh/vIQaJO0hQTVIsafWTAPBgNVHRMBAf8EBTAD\r\n"  \
"AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAw6tS6nTl4LdyqRoQULSMBU4whPINKlwrx\r\n"  \
"2PLJc9Ss32EoYUCRUPfVvevITB6EuCPl3v2kTHxKNxYK+APc90lUghLVKjkjoHeW\r\n"  \
"1Wc2G14rUS8o20/77k7yVZBM8/GPeABBgGqTgq2TLynWUsT/N+NCa9n1DH/M154m\r\n"  \
"10CmbOs3E0nTAVCbsW9u2YxisJpJ5FGKYgI9shb0Rgoyv7HNcYC7X+DcavYKoEzb\r\n"  \
"Vtd9dL4w4kCd6n5216ESTjXAwCKbOImI+iJq2R4WiC6BXCQSgsoIZtzP+JDlmO94\r\n"  \
"GnHxJMgzf3+NKdnNhF3qV2V+Lcb7O+MhFzRLNC5yVWnOkUx8MKla\r\n"  \
"-----END CERTIFICATE-----\r\n";
